apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: kinorgeportal
  app.kubernetes.io/name: umbraco

resources:
  - storage.yaml
  - serviceaccount.yaml
  - vault.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - network-policies.yaml
