apiVersion: v1
kind: ServiceAccount
metadata:
  name: umbraco
  annotations:
    azure.workload.identity/client-id: ${UMBRACO_CLIENT_ID}
    azure.workload.identity/tenant-id: cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c
    dis.altinn.cloud/principal-id: ${UMBRACO_PRINCIPAL_ID}
