apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-kinorgeportal
resources:
  - ../base

images:
  - name: umbraco
    newName: altinncr.azurecr.io/ghcr.io/digdir/ki.norge.no/umbraco
    newTag: will-be-replaced

patches:
  - target:
      kind: Vault
      name: umbraco
    patch: |-
      - op: add
        path: /spec/tags/env
        value: tt02
  - target:
      kind: Deployment
      name: umbraco
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__CMS__WebRouting__UmbracoApplicationUrl
          value: https://cms.ki.test.norge.no
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__CMS__Security__BackOfficeHost
          value: https://cms.ki.test.norge.no
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__Storage__AzureBlob__Media__ConnectionString
          value: https://kinorgemediatt0240c8.blob.core.windows.net
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__Storage__AzureBlob__Media__ContainerName
          value: umbraco
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: HeadlessPreview__FrontendUrl
          value: https://ki-norge-frontend-tt02.digitaliseringsdirektoratet.workers.dev
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Cloudflare__SiteBaseUrl
          value: https://ki.test.norge.no
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: uSync__Settings__DefaultSet
          value: Speiling
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: USYNC_OWNS_SCHEMA
          value: "true"
  - target:
      kind: HTTPRoute
      name: umbraco
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - kinorgeportal.tt02.dis-core.altinn.cloud
          - cms.ki.test.norge.no
          - cms-kinorgeportal-tt02.digitaliseringsdirektoratet.workers.dev
