apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-kinorge
resources:
  - ../base/umbraco-kinorge

images:
  - name: umbraco-kinorge
    newName: altinncr.azurecr.io/ghcr.io/altinn/umbraco-kinorge
    newTag: will-be-replaced

patches:
  - target:
      kind: Vault
      name: umbraco-kinorge
    patch: |-
      - op: add
        path: /spec/tags/env
        value: test
  - target:
      kind: Deployment
      name: umbraco-kinorge
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__Storage__AzureBlob__Media__ConnectionString
          value: https://kinorgemediatestXXXX.blob.core.windows.net
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__Storage__AzureBlob__Media__ContainerName
          value: umbraco
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__CMS__WebRouting__UmbracoApplicationUrl
          value: https://cms.test-ki.norge.no
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Umbraco__CMS__Security__BackOfficeHost
          value: https://cms.test-ki.norge.no
  - target:
      kind: HTTPRoute
      name: umbraco-kinorge
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - cms.test-ki.norge.no
